"""empty message

Revision ID: 053b64980759
Revises: 1adcdca7025d
Create Date: 2021-04-15 16:22:23.175280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053b64980759'
down_revision = '1adcdca7025d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('calories', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'calories')
    # ### end Alembic commands ###
